# Generated by Django 4.0.4 on 2022-07-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
