# Generated by Django 4.0.4 on 2022-07-17 22:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import trees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMaintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintained_on', models.DateTimeField(auto_now=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(upload_to=trees.models.image_location)),
                ('maintained_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_maintaince', to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainances', to='trees.tree')),
            ],
        ),
    ]
