# Generated by Django 4.0.4 on 2022-07-20 21:31

from django.db import migrations, models
import maintainance.models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemaintainance',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='treemaintainance',
            name='image',
            field=models.ImageField(upload_to=maintainance.models.image_location),
        ),
    ]
