# Generated by Django 4.0.4 on 2022-07-25 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.IntegerField(unique=True)),
                ('points', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreeAwarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=30)),
                ('object_id', models.PositiveIntegerField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardings', to='awarding.award')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardings', to='contenttypes.contenttype')),
            ],
        ),
    ]
