export { default as Home } from "./Home";
export { default as PlantersHome } from "./PlantersHome";
// export { default as Home } from "./Home";
export { default as ManageEmission } from "./ManageEmission";
export { default as NavBar } from "./NavBar";
export { default as PlantByHuman } from "./PlantByHuman";
export { default as PlantWithDrone } from "./PlantWithDrone";
export { default as HowItWorks } from "./HowItWorks";
export { default as Solution } from "./Solution";
export { default as Footer } from "./Footer";
export { default as DetectLocation } from "./DetectLocation";
export { default as UnderstandProcess } from "./UnderstandProcess";
export { default as SendLocation } from "./SendLocation";
export { default as ProcessSection } from "./ProcessSection";
