import React from "react";
import TreeBG from "../../assets/landing/home-bg.png";
import Drone from "../../assets/landing/Drone.png";
import calc from "../../assets/landing/calc.png";
import reduce from "../../assets/landing/reduce.png";
import offemission from "../../assets/landing/offemission.png";
import monitor from "../../assets/landing/monitor.png";
import analyze from "../../assets/landing/analyze.png";

const LandingPage = () => {
  const componentsArray = [
    {
      // background: BG1,
      Illustration: calc,
      TextList: {
        text: "The calculator allows you to convert your emissions of carbon dioxide to the equivalent amount of carbon-dioxide emissions generated by your actions and activities.",
        title: "ECalculate your carbon footprint",
      },
    },
    {
      // background: BG2,
      Illustration: reduce,
      TextList: {
        text: "One of the most immediate actions you can take to limit climate change is to reduce your emission. Our platform gives effective ways to reduce individual or organization carbon emissions.",
        title: "Reduce emission",
      },
    },
    {
      // background: BG3,
      Illustration: offemission,
      TextList: {
        text: "To compensate for your footprint, you can purchase carbon offset credit equivalent to the amount of emission you were responsible for. This will inform of any carbon reduction project.",
        title: "Offset emission ",
      },
    },
    {
      // background: BG3,
      Illustration: monitor,
      TextList: {
        text: "Tracking how much carbon dioxide is produced by particular activities at a particular time. With our database, we can gather and present the best available estimate of CO2 emission.",
        title: "Monitor emission ",
      },
    },
    {
      // background: BG3,
      Illustration: analyze,
      TextList: {
        text: "Get your overall carbon footprint, offset and reduction in one place and examine it. Check your contribution to the climate system.",
        title: "Analyze",
      },
    },
  ];

  function AmbassadorsInfo({ Pic, TextList }) {
    return (
      <div className="bg-white BG1 lg:w-3/11 px-5 h-370px flex flex-col items-flex-start justify-center mx-2 py-3rem lg:mb-4 mb-4 card">
        <div className="mb-8">
          <img
            src={Pic}
            alt="Location pins illustration"
            loading="lazy"
            className="w-3rem"
          />
        </div>
        <div className="text-left ">
          <h2 className="text-2xl lgreen my-2 font-bold md:text-3xl">
            {TextList.title}
          </h2>
          <p>{TextList.text}</p>
        </div>
      </div>
    );
  }

  return (
    <div>
      <section className=" grad-lgreen flex-wrap items-center justify-center  flex flex-col">
        <div className="container h-full  lg:mx-6 my-3 flex flex-col items-center justify-around lg:max-w-screen-xl px-2 py-2 lg:ml-12 lg:h-full  lg:items-center lg:flex text-zinc-800">
          <div className="lg:max-w-9/11 text-center darkgreen">
            <h1 className="text-3xl  sm:(text-7xl !leading-tight) font-medium capitalize text-zinc-800">
              Offset your carbon blueprint with
              <span className="lgreen"> GREEETH</span>
            </h1>

            <p className="mt-6 sm:leading-relaxed px-2 sm:text-xl">
              The best way for individuals and organizations to plant trees,
              offset their carbon footprint to save the planet.
            </p>
            <div className="gap-4 mt-10 mx-auto text-center w-1/2">
              <a
                className="block  py-4 text-base font-normal bg-lgreen rounded-lg shadow-md text-white sm:w-auto hover:text-white hover:bg-green-900 hover:border-white hover:border-2 active:text-rose-500 focus:outline-none focus:ring animate-bounce"
                href="/get-involved/sponsors/apply"
              >
                Plant Now
              </a>
            </div>
          </div>
          <div className="relative ">
            <img
              src={Drone}
              alt="Tree illustration"
              className="absolute left-0 sm:(top-30 w-13rem) top-10 w-7rem"
            />

            <img
              src={TreeBG}
              alt="Tree illustration"
              className="mx-auto lg:max-w-7/11"
            />
            <img
              src={Drone}
              alt="Tree illustration"
              className="absolute right-0 top-0 sm:w-13rem w-7rem"
            />
          </div>
        </div>
      </section>
      <div className="container bg-milkgreen h-full pt-20   flex flex-col items-center justify-around lg:max-w-screen-xl px-2 py-2  lg:h-full  lg:items-center lg:flex text-zinc-800">
        <div className="lg:max-w-9/11 text-center darkgreen">
          <h1 className="text-3xl  sm:(text-5xl !leading-tight) font-medium capitalize text-zinc-800">
            Manage your carbon emission
          </h1>

          <p className="mt-6 sm:leading-relaxed px-2 sm:text-lg">
            Take a step to measure and manage your carbon emission for yourself,
            your household, and your organization to mitigate the potential
            emission on the climate system.
          </p>
        </div>
        <div className="relative flex flex-wrap lg:flex-row flex-col items-center justify-center gap-1rem mt-2rem">
          {componentsArray.map((comp, i) => (
            <AmbassadorsInfo
              Pic={comp.Illustration}
              TextList={comp.TextList}
              Index={i}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default LandingPage;
