export const courses = [
	{
		coursename: "sustainability",
		stars: 5,
		rating: 15,
		duration: "3hr 36min",
		views: 306,

		courseid: 1,
		price: 100,
		courseDescription:
			"You can earn more money and boost your bottom line by making your business more sustainable. Reduced business costs, more innovative strategies, an improved reputation, and more new customers who value sustainability all work to increase the amount of money sustainable businesses earn.",
		moduleDescription: [
			"A business approach to creating long-term value by taking into consideration how a given organization operates in the ecological, social, and economic environments.",
			"Sustainability is built on the assumption that developing such strategies fosters company longevity.",
			"The goal of a sustainable business strategy is to make a positive impact on at least one of those areas.",
			"Another factor linking sustainability to value creation is the impact of corporate sustainability on a firm's cost of capital.",
			"When we focus on sustainability, the entire world benefits and gets to live in clean, more healthy living conditions.",
			"Enhanced Brand and Increased Competitive Advantage.",
			"Increased Productivity and Reduced Costs.",
			"Improve Financial and Investment Opportunity.",
			"Minimize Carbon Risk and Improve Energy Efficiency.",
			"Increase Employee Retention and Recruitment",
		],
		coursepic: "../assets/learing-assets/course1.png",
	},

	{
		coursename: "carbon offset",
		stars: 5,
		rating: 15,
		duration: "3hr 36min",
		views: 306,

		courseid: 2,
		price: 100,
		courseDescription:
			"You can earn more money and boost your bottom line by making your business more sustainable. Reduced business costs, more innovative strategies, an improved reputation, and more new customers who value sustainability all work to increase the amount of money sustainable businesses earn.",
		moduleDescription: [
			"A business approach to creating long-term value by taking into consideration how a given organization operates in the ecological, social, and economic environments.",
			"Sustainability is built on the assumption that developing such strategies fosters company longevity.",
			"The goal of a sustainable business strategy is to make a positive impact on at least one of those areas.",
			"Another factor linking sustainability to value creation is the impact of corporate sustainability on a firm's cost of capital.",
			"When we focus on sustainability, the entire world benefits and gets to live in clean, more healthy living conditions.",
			"Enhanced Brand and Increased Competitive Advantage.",
			"Increased Productivity and Reduced Costs.",
			"Improve Financial and Investment Opportunity.",
			"Minimize Carbon Risk and Improve Energy Efficiency.",
			"Increase Employee Retention and Recruitment",
		],
		coursepic: "../assets/learing-assets/course2.png",
	},
	{
		coursename: "climate change",
		stars: 5,
		rating: 15,
		duration: "3hr 36min",
		views: 306,

		courseid: 2,
		price: 100,
		courseDescription:
			"You can earn more money and boost your bottom line by making your business more sustainable. Reduced business costs, more innovative strategies, an improved reputation, and more new customers who value sustainability all work to increase the amount of money sustainable businesses earn.",
		moduleDescription: [
			"A business approach to creating long-term value by taking into consideration how a given organization operates in the ecological, social, and economic environments.",
			"Sustainability is built on the assumption that developing such strategies fosters company longevity.",
			"The goal of a sustainable business strategy is to make a positive impact on at least one of those areas.",
			"Another factor linking sustainability to value creation is the impact of corporate sustainability on a firm's cost of capital.",
			"When we focus on sustainability, the entire world benefits and gets to live in clean, more healthy living conditions.",
			"Enhanced Brand and Increased Competitive Advantage.",
			"Increased Productivity and Reduced Costs.",
			"Improve Financial and Investment Opportunity.",
			"Minimize Carbon Risk and Improve Energy Efficiency.",
			"Increase Employee Retention and Recruitment",
		],
		coursepic: "../assets/learing-assets/course3.png",
	},

	{
		coursename: "carbon footprint",
		stars: 5,
		rating: 15,
		duration: "3hr 36min",
		views: 306,

		courseid: 2,
		price: 100,
		courseDescription:
			"You can earn more money and boost your bottom line by making your business more sustainable. Reduced business costs, more innovative strategies, an improved reputation, and more new customers who value sustainability all work to increase the amount of money sustainable businesses earn.",
		moduleDescription: [
			"A business approach to creating long-term value by taking into consideration how a given organization operates in the ecological, social, and economic environments.",
			"Sustainability is built on the assumption that developing such strategies fosters company longevity.",
			"The goal of a sustainable business strategy is to make a positive impact on at least one of those areas.",
			"Another factor linking sustainability to value creation is the impact of corporate sustainability on a firm's cost of capital.",
			"When we focus on sustainability, the entire world benefits and gets to live in clean, more healthy living conditions.",
			"Enhanced Brand and Increased Competitive Advantage.",
			"Increased Productivity and Reduced Costs.",
			"Improve Financial and Investment Opportunity.",
			"Minimize Carbon Risk and Improve Energy Efficiency.",
			"Increase Employee Retention and Recruitment",
		],
		coursepic: "../assets/learing-assets/course4.png",
	},

	{
		coursename: "tree planting",
		stars: 5,
		rating: 15,
		duration: "3hr 36min",
		views: 306,

		courseid: 2,
		price: 100,
		courseDescription:
			"You can earn more money and boost your bottom line by making your business more sustainable. Reduced business costs, more innovative strategies, an improved reputation, and more new customers who value sustainability all work to increase the amount of money sustainable businesses earn.",
		moduleDescription: [
			"A business approach to creating long-term value by taking into consideration how a given organization operates in the ecological, social, and economic environments.",
			"Sustainability is built on the assumption that developing such strategies fosters company longevity.",
			"The goal of a sustainable business strategy is to make a positive impact on at least one of those areas.",
			"Another factor linking sustainability to value creation is the impact of corporate sustainability on a firm's cost of capital.",
			"When we focus on sustainability, the entire world benefits and gets to live in clean, more healthy living conditions.",
			"Enhanced Brand and Increased Competitive Advantage.",
			"Increased Productivity and Reduced Costs.",
			"Improve Financial and Investment Opportunity.",
			"Minimize Carbon Risk and Improve Energy Efficiency.",
			"Increase Employee Retention and Recruitment",
		],
		coursepic: "../assets/learing-assets/course5.png",
	},

	{
		coursename: "silviculture",
		stars: 5,
		rating: 15,
		duration: "3hr 36min",
		views: 306,

		courseid: 2,
		price: 100,
		courseDescription:
			"You can earn more money and boost your bottom line by making your business more sustainable. Reduced business costs, more innovative strategies, an improved reputation, and more new customers who value sustainability all work to increase the amount of money sustainable businesses earn.",
		moduleDescription: [
			"A business approach to creating long-term value by taking into consideration how a given organization operates in the ecological, social, and economic environments.",
			"Sustainability is built on the assumption that developing such strategies fosters company longevity.",
			"The goal of a sustainable business strategy is to make a positive impact on at least one of those areas.",
			"Another factor linking sustainability to value creation is the impact of corporate sustainability on a firm's cost of capital.",
			"When we focus on sustainability, the entire world benefits and gets to live in clean, more healthy living conditions.",
			"Enhanced Brand and Increased Competitive Advantage.",
			"Increased Productivity and Reduced Costs.",
			"Improve Financial and Investment Opportunity.",
			"Minimize Carbon Risk and Improve Energy Efficiency.",
			"Increase Employee Retention and Recruitment",
		],
		coursepic: "../assets/learing-assets/course6.png",
	},
	{
		coursename: "carbon footprint",
		stars: 5,
		rating: 15,
		duration: "3hr 36min",
		views: 306,

		courseid: 2,
		price: 100,
		courseDescription:
			"You can earn more money and boost your bottom line by making your business more sustainable. Reduced business costs, more innovative strategies, an improved reputation, and more new customers who value sustainability all work to increase the amount of money sustainable businesses earn.",
		moduleDescription: [
			"A business approach to creating long-term value by taking into consideration how a given organization operates in the ecological, social, and economic environments.",
			"Sustainability is built on the assumption that developing such strategies fosters company longevity.",
			"The goal of a sustainable business strategy is to make a positive impact on at least one of those areas.",
			"Another factor linking sustainability to value creation is the impact of corporate sustainability on a firm's cost of capital.",
			"When we focus on sustainability, the entire world benefits and gets to live in clean, more healthy living conditions.",
			"Enhanced Brand and Increased Competitive Advantage.",
			"Increased Productivity and Reduced Costs.",
			"Improve Financial and Investment Opportunity.",
			"Minimize Carbon Risk and Improve Energy Efficiency.",
			"Increase Employee Retention and Recruitment",
		],
		coursepic: "../assets/learing-assets/course7.png",
	},

	{
		coursename: "tree planting",
		stars: 5,
		rating: 15,
		duration: "3hr 36min",
		views: 306,

		courseid: 2,
		price: 100,
		courseDescription:
			"You can earn more money and boost your bottom line by making your business more sustainable. Reduced business costs, more innovative strategies, an improved reputation, and more new customers who value sustainability all work to increase the amount of money sustainable businesses earn.",
		moduleDescription: [
			"A business approach to creating long-term value by taking into consideration how a given organization operates in the ecological, social, and economic environments.",
			"Sustainability is built on the assumption that developing such strategies fosters company longevity.",
			"The goal of a sustainable business strategy is to make a positive impact on at least one of those areas.",
			"Another factor linking sustainability to value creation is the impact of corporate sustainability on a firm's cost of capital.",
			"When we focus on sustainability, the entire world benefits and gets to live in clean, more healthy living conditions.",
			"Enhanced Brand and Increased Competitive Advantage.",
			"Increased Productivity and Reduced Costs.",
			"Improve Financial and Investment Opportunity.",
			"Minimize Carbon Risk and Improve Energy Efficiency.",
			"Increase Employee Retention and Recruitment",
		],
		coursepic: "../assets/learing-assets/course8.png",
	},

	{
		coursename: "siviculture",
		stars: 5,
		rating: 15,
		duration: "3hr 36min",
		views: 306,

		courseid: 2,
		price: 100,
		courseDescription:
			"You can earn more money and boost your bottom line by making your business more sustainable. Reduced business costs, more innovative strategies, an improved reputation, and more new customers who value sustainability all work to increase the amount of money sustainable businesses earn.",
		moduleDescription: [
			"A business approach to creating long-term value by taking into consideration how a given organization operates in the ecological, social, and economic environments.",
			"Sustainability is built on the assumption that developing such strategies fosters company longevity.",
			"The goal of a sustainable business strategy is to make a positive impact on at least one of those areas.",
			"Another factor linking sustainability to value creation is the impact of corporate sustainability on a firm's cost of capital.",
			"When we focus on sustainability, the entire world benefits and gets to live in clean, more healthy living conditions.",
			"Enhanced Brand and Increased Competitive Advantage.",
			"Increased Productivity and Reduced Costs.",
			"Improve Financial and Investment Opportunity.",
			"Minimize Carbon Risk and Improve Energy Efficiency.",
			"Increase Employee Retention and Recruitment",
		],
		coursepic: "../assets/learing-assets/course9.png",
	},
];
