# Generated by Django 4.0.4 on 2022-07-29 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trees', '0002_alter_tree_created_on_alter_tree_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('share_code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('recepient_email', models.EmailField(max_length=254)),
                ('received_on', models.DateTimeField(null=True)),
                ('recepient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_trees', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trees', to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared', to='trees.tree')),
            ],
        ),
    ]
